-- SQL schema for Supabase
-- Create tables for AbogApp

create table clientes (
    id bigint generated by default as identity primary key,
    app_id bigint unique,
    nombre text not null,
    correo text,
    telefono text,
    direccion text,
    rut text,
    confidencial text,
    link text,
    cotizaciones jsonb,
    creado_por text,
    created_at timestamp with time zone default current_timestamp,
    updated_at timestamp with time zone default current_timestamp
);

-- Tabla de tareas del día activas
create table diario (
    id bigint generated by default as identity primary key,
    app_id bigint unique,
    texto text not null,
    asignados jsonb,
    fecha_fin date,
    prioridad text,
    comentarios jsonb,
    creado_en timestamp with time zone default current_timestamp
);

-- Tabla de tareas del día archivadas
create table diarioarchivadas (
    id bigint generated by default as identity primary key,
    app_id bigint unique,
    texto text not null,
    asignados jsonb,
    fecha_fin date,
    prioridad text,
    comentarios jsonb,
    creado_en timestamp with time zone default current_timestamp,
    archivado_por text,
    archivado_en timestamp with time zone default current_timestamp
);

-- Tabla de tareas internas
create table tareasinternas (
    id bigint generated by default as identity primary key,
    app_id bigint unique,
    texto text not null,
    asignados jsonb,
    fecha_fin date,
    prioridad text,
    comentarios jsonb,
    creado_en timestamp with time zone default current_timestamp,
    archivado_por text,
    archivado_en timestamp with time zone default current_timestamp
);

-- Tabla de audiencias activas
create table audiencias (
    id bigint generated by default as identity primary key,
    app_id bigint unique,
    titulo text not null,
    tipo text,
    modalidad text,
    fecha date,
    hora time,
    notas text,
    creado_por text,
    created_at timestamp with time zone default current_timestamp
);

-- Tabla de audiencias archivadas
create table audienciasarchivadas (
    id bigint generated by default as identity primary key,
    app_id bigint unique,
    titulo text not null,
    tipo text,
    modalidad text,
    fecha date,
    hora time,
    notas text,
    creado_por text,
    archivado_por text,
    archivado_en timestamp with time zone default current_timestamp
);

-- Comentarios asociados a clientes
create table comentarios_clientes (
    id bigint generated by default as identity primary key,
    app_id bigint unique,
    cliente_id bigint references clientes(app_id) on delete cascade,
    texto text not null,
    creado_por text,
    created_at timestamp with time zone default current_timestamp
);

-- Notificaciones generadas por la aplicación
create table notificaciones (
    id bigint generated by default as identity primary key,
    app_id bigint unique,
    mensaje text not null,
    destino text,
    creado_por text,
    created_at timestamp with time zone default current_timestamp
);

-- Contador para cotizaciones emitidas
create table cotizaciones (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default current_timestamp
);

alter sequence cotizaciones_id_seq restart with 182;

-- Tema visual preferido por cada usuario
create table temas_usuarios (
    id bigint generated by default as identity primary key,
    usuario text unique,
    tema text,
    created_at timestamp with time zone default current_timestamp,
    updated_at timestamp with time zone default current_timestamp
);
