<?php
return [
    'db_host' => 'localhost',
    'db_name' => 'cpanel_database',
    'db_user' => 'cpanel_user',
    'db_pass' => 'REEMPLAZAR_PASSWORD',
    'api_key' => 'REEMPLAZAR_API_KEY',
    'timezone' => 'America/Santiago',
    'google_calendar_id' => 'REEMPLAZAR_CALENDAR_ID',
    'google_service_account_json_path' => __DIR__ . '/service-account.json',
    'google_keywords' => ['preparatoria', 'monitorio', 'alegato', 'juicio', 'audiencia', 'comparendo', 'cautelar'],
    'google_sync_days_back' => 90,
    'mail_from' => 'no-reply@tu-dominio.cl',
    'mail_from_name' => 'Abogapp',
    'task_reminders_hour' => 9,
    'task_reminders_minute' => 0,
    'task_reminders_cron_secret' => 'REEMPLAZAR_SECRET_CRON',
    'whatsapp_enabled' => false,
    'whatsapp_api_version' => 'v20.0',
    'whatsapp_phone_number_id' => 'REEMPLAZAR_PHONE_NUMBER_ID',
    'whatsapp_access_token' => 'REEMPLAZAR_ACCESS_TOKEN',
    'template_assignment_subject' => 'Nueva tarea asignada: {{titulo}}',
    'template_assignment_body' => 'Estimado {{nombre}}, se te asignó una tarea en Abogapp.',
    'template_digest_subject' => 'Recordatorio diario 09:00 - Tareas pendientes',
    'template_digest_intro' => 'Este es tu resumen diario de tareas pendientes en Abogapp ({{fecha}}).',
];
